system:
  A0: 1e-7
  theta_incidence: 30  # in degrees
  k_magnitude: 314.159  # 2 * pi / 0.02
  f: 1000
  lambda_laser: 1e-6

reconstruction:
  r: 0.01
  x0: 0.0
  y0: 0.0

grid:
  x_range: [-0.01, 0.01]
  y_range: [-0.01, 0.01]
  t_range: [0, 0.001]
  x_points: 64
  y_points: 64
  t_points: 10

optimization:
  theta_range: [0, 90]  # in degrees
  theta_points: 181